[package]
name = "modpackr-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dotenv = "0.15.0"
anyhow = "1.0.98"

[dependencies.modpackr]
path = "../"
